name: Build Debian ISO with Preseed in initrd

on:
  push:
    branches: [ main ]

env:
  ISO_SUFFIX_NAME: debian-snoopy-preseed
  DEBIAN_ISO_URL: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.11.0-amd64-netinst.iso
  DEBIAN_ISO_FILE: debian-netinst.iso

jobs:
  build-preseed-debian-installer-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y genisoimage syslinux-utils libarchive-tools

      - name: Download Debian ISO
        run: |
          wget -O "${{ env.DEBIAN_ISO_FILE }}" "${{ env.DEBIAN_ISO_URL }}"

      - name: Extract ISO and copy contents
        run: |
          mkdir -p iso-new
          bsdtar -C iso-new -xf "${{ env.DEBIAN_ISO_FILE }}"
          chmod -R u+w iso-new

      - name: Embed preseed.cfg into initrd
        run: |
          chmod +w -R iso-new/install.amd/
          gunzip iso-new/install.amd/initrd.gz
          echo preseed.cfg | cpio -H newc -o -A -F iso-new/install.amd/initrd
          gzip iso-new/install.amd/initrd
          chmod -w -R iso-new/install.amd/

      - name: Update md5sum.txt
        run: |
          cd iso-new
          chmod +w md5sum.txt
          find -follow -type f ! -name md5sum.txt -print0 | xargs -0 md5sum > md5sum.txt
          chmod -w md5sum.txt
          cd ..

      - name: Build new ISO
        run: |
          ISO_NAME="${{ env.ISO_SUFFIX_NAME }}-$(date +%Y%m%d%H%M%S).iso"
          genisoimage -r -J \
            -b isolinux/isolinux.bin -c isolinux/boot.cat \
            -no-emul-boot -boot-load-size 4 -boot-info-table \
            -o "$ISO_NAME" iso-new

          echo "ISO_NAME=$ISO_NAME" >> $GITHUB_ENV

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ISO_NAME }}
          path: ${{ env.ISO_NAME }}
